### ISSUE TITLE
1 fail in spanish

### ISSUE THREAD

**Issue by Ivraie** [yamadapc/js-written-number#34]
Hi, Very cleaver and simple approach. Thanks !
I was wondering if there is not an issue with 1 in Spanish. I'm not spanish but it seems that 1 would convert to "uno" but it converts to "un" instead. 

      writtenNumber(1).should.equal('uno');

Regards !
Ant.

**Comment by yamadapc** [comment]
Hey @Invraie, thanks for filling a bug. I'm not a Spanish speaker either, that was an external contribution from @maxiruani.

I think you're right though. There're exceptions so:
```javascript
writtenNumber(1000000).should.equal('un million');
```

Works.

- - -

Something in the beginning conditionals should be changed so `1` or `X...1` work as expected.

There're quite a few languages I'm not fluent with here, but I'll have a better look today and take a shot at fixing it.

**Comment by Ivraie** [comment]
Hi @yamadapc ,
Thanks for your reply. I found the bug because I'm trying to implements Italian. But I'm not an Italian speaker...
I had to modify the way separator works, since Italian doesn't separate number , for example : 
1984 -> mille­nove­cent­ottanta­quattro

**Comment by CoriAle** [comment]
I do speak spanish, and the correct representation of  1 would be "Uno", but writtenNumber(1) keeps returning "un".
