### ISSUE TITLE
Do not round decimal number

### ISSUE THREAD

**Issue by Trioblack** [yamadapc/js-written-number#45]
Hey, guys.

How can I avoid rounding up numbers?
Here: 342 877,50
I expect: **trezentos e quarenta e dois mil oitocentos e setenta e sete e cinquenta cêntimos**
I got: **trezentos e quarenta e dois mil oitocentos e setenta e oito**

Thanks

**Comment by yamadapc** [comment]
That's not implemented

**Comment by yamadapc** [comment]
Closing as #2 already exists, PR's are wanted and accepted, but there's a non-negligible amount of work involved. Starting with one language would be ok.

**Comment by Trioblack** [comment]
Sure. Thanks!
