### ISSUE TITLE
Last version on NPM is 0.9.1

### ISSUE THREAD

**Issue by Demuzx** [yamadapc/js-written-number#68]
"npm install --save written-number" last version in NPM is 0.9.1, not 0.11.0.

**Comment by georgyfarniev** [comment]
Cast @yamadapc

**Comment by forzagreen** [comment]
@georgyfarniev @Demuzx 
We started a new project at https://github.com/forzagreen/n2words . Already supporting 20 languages !
Give it a try, and feel free to contribute ! ;)

```
npm install n2words
```

**Comment by yamadapc** [comment]
I've published `v0.11.0`. 

Thanks for linking your project @forzagreen.
